apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: aierohin/nginx:$BUILD_NUMBER
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: nginx
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 80
      nodePort: 30001
  selector:
    app: nginx
